configure infrastructure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -231,177 +231,58 @@ jobs:
 
 
 
-# configure-infrastructure:
-#   docker:
-#     - image: cimg/base:stable 
-#       # Docker image here that supports Ansible
 
-#   steps:
-#     - checkout #-code from git
-#     - add_ssh_keys:
-#         - fingerprint:
-#             - "a8:d0:51:94:4d:08:c5:78:55:d1:35:a8:47:8d:67:5d"
-#     - attach_workspace: 
-#         at: ~/
-#     - install_ansible
-#     - run:
-#         name: Configure server
-#         command: |
-#             # Your code here
-#           cd .circlci/ansible
-#           cat inventory.txt
-#           ansible-playbook -i inventory.txt configure-server.yml
-#           exit 1
-#       # Here's where you will add some code to rollback on failure      
-#     - destroy_environment
 
 configure-infrastructure:
-    executor: python
-    steps:
-      - checkout
+   docker:
+      # Docker image here that supports Ansible
+      - image: cimg/base:stable 
+   steps:
+      - Checkout #-code from git
       - add_ssh_keys:
-          fingerprints: ["a8:d0:51:94:4d:08:c5:78:55:d1:35:a8:47:8d:67:5d"]
-      - attach_workspace:
-          at: .
-      - run:
-          name: Install dependencies
-          working_directory: ./.circleci/ansible
-          command: |
-            apk add --update ansible
-            ansible --version
+          - fingerprint:
+              - "a8:d0:51:94:4d:08:c5:78:55:d1:35:a8:47:8d:67:5d"
+       #Add ssh keys with fingerprint
+      - attach_workspace: #attach workspace
+          at: ~/
+      - install_ansible
       - run:
           name: Configure server
-          working_directory: ./.circleci/ansible
           command: |
-            pwd &&
-            ls -la
-            cat inventory
-            ansible-playbook -i inventory configure-server.yaml
-      - destroy_environment:
-          id: ${CIRCLE_WORKFLOW_ID:0:7}
-          when: on_fail
-
+            # Your code here
+            cd .circlci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt configure-server.yml
+            exit 1
+      - destroy-environment
+      # Here's where you will add some code to rollback on failure      
 
 run-migrations:
-    executor: node
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Install AWS CLI dependencies
-          working_directory: /tmp
-          command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+      # Checkout code from git
       - run:
           name: Run migrations
-          working_directory: ./backend
           command: |
-            npm run migrations > migration_status
+            # Your code here
+            cd  backend
+            npm install
+            npm run migration > migration_dump.txt
+            exit 1
       - run:
           name: Send migration results to memstash
-          working_directory: ./backend
           command: |
-            if grep -q "has been executed successfully" migration_status
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-              echo "DB migration was successful, will update memstash..."
-              curl -H "Content-Type: text/plain" -H "token: 2a9e15d6-b9fa-4b1f-a5dc-e3b9643a9b63" --request PUT --data "success" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
-            else
-              echo "DB migration failed, please verify setup! Probably the database already exists. Verify setup!"
-              curl -H "Content-Type: text/plain" -H "token: 2a9e15d6-b9fa-4b1f-a5dc-e3b9643a9b63" --request PUT --data "failure" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
+             cul --insecure https://kvdb.io/5dR7n4E8kRzBgGRhLTTrZu/migration_${CIRCLE_WORKFLOW_ID:0:7} -D '1'
             fi
-            echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
-      - destroy_environment:
-          id: ${CIRCLE_WORKFLOW_ID:0:7}
-          when: on_fail
-
-
-
-
-# run-migrations:
-#   docker:
-#       # Docker image here that supports NodeJS
-#     - image: circleci/node:13.8.0
-#   steps:
-#     - checkout
-#     - run:
-#         name: Run migrations
-#         command: |
-#             # Your code here
-#           cd  backend
-#           npm install
-#           npm run migration > migration_dump.txt
-            
-#     - run:
-#         name: Send migration results to memstash
-#         command: |
-#             # Your code here
-#           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-#           then
-#             cul --insecure https://kvdb.io/${(KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -D '1'
-#           fi
-#     - destroy_environment
-#     - revert_migrations
-            
-     # Here's where you will add some code to rollback on failure    
-
-
-
-# configure-infrastructure:
-#    docker:
-#       # Docker image here that supports Ansible
-#       - image: cimg/base:stable 
-#    steps:
-#       - Checkout #-code from git
-#       - add_ssh_keys:
-#           - fingerprint:
-#               - "a8:d0:51:94:4d:08:c5:78:55:d1:35:a8:47:8d:67:5d"
-#        #Add ssh keys with fingerprint
-#       - attach_workspace: #attach workspace
-#           at: ~/
-#       - install_ansible
-#       - run:
-#           name: Configure server
-#           command: |
-#             # Your code here
-#             cd .circlci/ansible
-#             cat inventory.txt
-#             ansible-playbook -i inventory.txt configure-server.yml
-#             exit 1
-#       - destroy-environment
-#       # Here's where you will add some code to rollback on failure      
-
-# run-migrations:
-#     docker:
-#       # Docker image here that supports NodeJS
-#       - image: circleci/node:13.8.0
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Run migrations
-#           command: |
-#             # Your code here
-#             cd  backend
-#             npm install
-#             npm run migration > migration_dump.txt
-#             exit 1
-#       - run:
-#           name: Send migration results to memstash
-#           command: |
-#             # Your code here
-#             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-#             then
-#              cul --insecure https://kvdb.io/${(KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -D '1'
-#             fi
-#       - destroy_environment
-#       - revert_migrations
-#             exit 1
-#      # Here's where you will add some code to rollback on failure 
-
-
+      - destroy_environment
+      - revert_migrations
+            exit 1
+     # Here's where you will add some code to rollback on failure 
 
 
 workflows:
