configure infrastructure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,7 +19,55 @@ executors:
     docker:
       - image: amazon/aws-cli
 
-
+commands:
+  install_ansible:
+    description: install Ansible
+    steps:
+    - run:
+        name: Install ansible
+        command: |
+          sudo apt update
+          sudo apt install software-properties-common -y
+          sudo add-apt-repository --yes -update ppa:ansible/ansible
+          sudo apt install ansible -y
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      # Add parameter here  
+      workflow_id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            # Your code here
+            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
+            exit 1
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here 
+      workflow_id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string    
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = $(curl --request GET https://api.memstash.io/values/DB_MIGRATION_<< parameters.workflow_id >>)
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+              Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
 jobs:
   
   build-frontend:
@@ -182,6 +230,65 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
 
+configure-infrastructure:
+    docker:
+      # Docker image here that supports Ansible
+      - image: cimg/base:stable 
+    steps:
+      - Checkout #-code from git
+      - add_ssh_keys:
+          - fingerprint:
+              - "a8:d0:51:94:4d:08:c5:78:55:d1:35:a8:47:8d:67:5d"
+       #Add ssh keys with fingerprint
+      - attach_workspace: #attach workspace
+          at: ~/
+      - install_ansible
+      # - run:
+      #     name: Install dependencies
+      #     command: |
+      #       # Your code here
+      #       exit 1
+      - run:
+          name: Configure server
+          command: |
+            # Your code here
+            cd .circlci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt configure-server.yml
+            exit 1
+      - destroy-environment
+      # Here's where you will add some code to rollback on failure      
+
+run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd  backend
+            npm install
+            npm run migration > migration_dump.txt
+            exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+             cul --insecure https://kvdb.io/${(KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -D '1'
+            fi
+      - destroy_environment
+      - revert_migrations
+            exit 1
+     # Here's where you will add some code to rollback on failure 
+
+
+
+
 workflows:
   workflow-project:
     jobs:
@@ -204,4 +311,7 @@ workflows:
           filters:
             branches:
               only: [master]
-
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
